#!/usr/bin/env python3
"""
Generate the soft-glow blob bitmap used by the Aino-bot face renderer.

Emits a 24×24 alpha mask as a C uint8_t[576] header. Each pixel is one byte
0..255 representing additive-glow intensity. The firmware multiplies this by
the active fg color and blits it (additive blend) centered on every lit cell.

Why alpha instead of RGB565: storing intensity-only lets the renderer tint per
palette without rebaking. 576 bytes is also tinier than the equivalent RGB565
(~1.1 KB) and survives well into other emotion colors.

Distribution: Gaussian with σ = 4.5 device px, normalized to peak 255.

Usage:
    python3 gen_glow.py > ../main/stackchan/avatar/skins/aino/aino_glow.h

Requires numpy.
"""
import sys
import math
import numpy as np

SIZE = 24      # blob is SIZE × SIZE
SIGMA = 4.5    # Gaussian σ in device pixels

def main() -> None:
    cx = (SIZE - 1) / 2.0
    cy = (SIZE - 1) / 2.0
    g = np.zeros((SIZE, SIZE), dtype=np.float64)
    for y in range(SIZE):
        for x in range(SIZE):
            d2 = (x - cx) ** 2 + (y - cy) ** 2
            g[y, x] = math.exp(-d2 / (2.0 * SIGMA * SIGMA))
    g = (g / g.max()) * 255.0
    g = g.clip(0, 255).astype(np.uint8)

    out = sys.stdout
    out.write("/*\n")
    out.write(" * SPDX-FileCopyrightText: 2026 koshisan\n")
    out.write(" * SPDX-License-Identifier: MIT\n")
    out.write(" *\n")
    out.write(" * GENERATED by firmware/tools/gen_glow.py. Do not edit by hand.\n")
    out.write(f" * 24×24 alpha mask, Gaussian σ={SIGMA}, peak 255.\n")
    out.write(" */\n")
    out.write("#pragma once\n")
    out.write("#include <cstdint>\n\n")
    out.write("namespace stackchan::avatar::aino {\n\n")
    out.write(f"inline constexpr int GLOW_SIZE = {SIZE};\n\n")
    out.write("inline constexpr uint8_t GLOW_ALPHA[] = {\n")
    for y in range(SIZE):
        row = ", ".join(f"{int(v):3d}" for v in g[y])
        out.write(f"    {row},\n")
    out.write("};\n\n")
    out.write("}  // namespace stackchan::avatar::aino\n")

if __name__ == "__main__":
    main()
